sudo: false
language: cpp

install:
    - export CC="${MY_CC}"
    - export CXX="${MY_CXX}"
    - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then ./ci_scripts/travis_ci_install_osx.sh; fi"

script: 
    - export CC="${MY_CC}"
    - export CXX="${MY_CXX}"
    - mkdir build
    - cd build
    - cmake ../
    - make
    - make test

matrix:
  include:
    - os: linux
      compiler: gcc
      env: 
        - MY_CC=gcc-4.8
        - MY_CXX=g++-4.8
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-4.8
            - cmake
            - cmake-data
    - os: linux
      compiler: gcc
      env: 
        - MY_CC=gcc-4.9
        - MY_CXX=g++-4.9
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-4.9
            - cmake
            - cmake-data
    - os: linux
      compiler: gcc
      env: 
        - MY_CC=gcc-5
        - MY_CXX=g++-5
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-5
            - cmake
            - cmake-data
    - os: linux
      compiler: clang
      env: 
        - MY_CC=clang-3.5
        - MY_CXX=clang++-3.5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5
            - george-edison55-precise-backports
          packages:
            - g++-4.8 # Always install latest GCC 4.8 to avoid bugs in old STL when compiling with Clang
            - clang-3.5
            - cmake
            - cmake-data
    - os: linux
      compiler: clang
      env: 
        - MY_CC=clang-3.6
        - MY_CXX=clang++-3.6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - george-edison55-precise-backports
          packages:
            - g++-4.8 # Always install latest GCC 4.8 to avoid bugs in old STL when compiling with Clang
            - clang-3.6
            - cmake
            - cmake-data
    - os: linux
      compiler: clang
      env: 
        - MY_CC=clang-3.7
        - MY_CXX=clang++-3.7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - george-edison55-precise-backports
          packages:
            - g++-4.8 # Always install latest GCC 4.8 to avoid bugs in old STL when compiling with Clang
            - clang-3.7
            - cmake
            - cmake-data
    - os: linux
      compiler: clang
      env: 
        - MY_CC=clang-3.8
        - MY_CXX=clang++-3.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
            - george-edison55-precise-backports
          packages:
            - g++-4.8 # Always install latest GCC 4.8 to avoid bugs in old STL when compiling with Clang
            - clang-3.8
            - cmake
            - cmake-data
    - os: osx
      compiler: gcc
      env: 
        - MY_CC=gcc-4.8
        - MY_CXX=g++-4.8
    - os: osx
      compiler: gcc
      env: 
        - MY_CC=gcc-4.9
        - MY_CXX=g++-4.9
    - os: osx
      compiler: gcc
      env: 
        - MY_CC=gcc-5
        - MY_CXX=g++-5
    - os: osx
      compiler: clang
      env: 
        - MY_CC=clang-3.7
        - MY_CXX=clang++-3.7
    - os: osx
      compiler: clang
      env: 
        - MY_CC=clang-3.8
        - MY_CXX=clang++-3.8
