sudo: false
language: cpp

services:
    - docker

install:
    - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then source ci_scripts/travis_ci_install_osx.sh; fi"

script: 
    - "if [ ${TRAVIS_OS_NAME} = 'linux' ]; then make generate_linux build_linux test_linux; fi"
    - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then make generate_osx build_osx test_osx; fi"

matrix:
  include:
    - os: linux
      compiler: gcc
      env: 
        - COMPILER=gcc
        - VERSION=4.9
    - os: linux
      compiler: gcc
      env: 
        - COMPILER=gcc
        - VERSION=5
    - os: linux
      compiler: gcc
      env: 
        - COMPILER=gcc
        - VERSION=6
    - os: linux
      compiler: gcc
      env: 
        - COMPILER=gcc
        - VERSION=7
    - os: linux
      compiler: gcc
      env: 
        - COMPILER=gcc
        - VERSION=8
    - os: linux
      compiler: gcc
      env: 
        - COMPILER=gcc
        - VERSION=9
    - os: linux
      compiler: clang
      env: 
        - COMPILER=clang
        - VERSION=3.7
    - os: linux
      compiler: clang
      env: 
        - COMPILER=clang
        - VERSION=3.8
    - os: linux
      compiler: clang
      env: 
        - COMPILER=clang
        - VERSION=3.9
    - os: linux
      compiler: clang
      env: 
        - COMPILER=clang
        - VERSION=4
    - os: linux
      compiler: clang
      env: 
        - COMPILER=clang
        - VERSION=5
    - os: linux
      compiler: clang
      env: 
        - COMPILER=clang
        - VERSION=6
    - os: linux
      compiler: clang
      env: 
        - COMPILER=clang
        - VERSION=7
    - os: osx
      compiler: gcc
      env: 
        - COMPILER=gcc
        - VERSION=4.9
    - os: osx
      compiler: gcc
      env: 
        - COMPILER=gcc
        - VERSION=6
    - os: osx
      compiler: gcc
      env: 
        - COMPILER=gcc
        - VERSION=7
    - os: osx
      compiler: gcc
      env: 
        - COMPILER=gcc
        - VERSION=8
    - os: osx
      compiler: clang
      env: 
        - COMPILER=clang
        - VERSION=3.9
    - os: osx
      compiler: clang
      env: 
        - COMPILER=clang
        - VERSION=4
    - os: osx
      compiler: clang
      env: 
        - COMPILER=clang
        - VERSION=5
    - os: osx
      compiler: clang
      env: 
        - COMPILER=clang
        - VERSION=6
    - os: osx
      compiler: clang
      env: 
        - COMPILER=clang
        - VERSION=7
